import { VendorData, ProblemSummary } from '../types';

const CATEGORY_TO_PLACES_TYPE: Record<ProblemSummary['category'], string> = {
  hvac: 'heating_contractor',
  plumber: 'plumber',
  electrician: 'electrician',
  roofer: 'roofing_contractor',
  appliance: 'appliance_repair_service',
  pest: 'pest_control_service',
  general: 'general_contractor'
};

// Sample vendor data for demonstration
const SAMPLE_VENDORS: Record<string, VendorData[]> = {
  hvac: [
    {
      id: 'hvac-1',
      name: 'Comfort Zone HVAC',
      rating: 4.8,
      reviewCount: 127,
      phone: '(555) 123-4567',
      website: 'https://comfortzonehvac.com',
      address: '123 Main St, Springfield',
      distance: 2.3,
      category: 'HVAC',
      hasWebChat: true,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'hvac-2',
      name: 'ABC Heating & Cooling',
      rating: 4.5,
      reviewCount: 89,
      phone: '(555) 234-5678',
      address: '456 Oak Ave, Springfield',
      distance: 3.1,
      category: 'HVAC',
      hasWebChat: false,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'hvac-3',
      name: 'Quick Fix HVAC Services',
      rating: 4.9,
      reviewCount: 203,
      phone: '(555) 345-6789',
      website: 'https://quickfixhvac.com',
      address: '789 Pine St, Springfield',
      distance: 4.7,
      category: 'HVAC',
      hasWebChat: true,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'hvac-4',
      name: 'Premier Climate Control',
      rating: 4.6,
      reviewCount: 156,
      phone: '(555) 456-7890',
      website: 'https://premierclimate.com',
      address: '321 Climate Dr, Springfield',
      distance: 5.2,
      category: 'HVAC',
      hasWebChat: true,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'hvac-5',
      name: 'Reliable Air Systems',
      rating: 4.7,
      reviewCount: 98,
      phone: '(555) 567-8901',
      address: '654 Air Way, Springfield',
      distance: 6.1,
      category: 'HVAC',
      hasWebChat: false,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'hvac-6',
      name: 'Express HVAC Repair',
      rating: 4.4,
      reviewCount: 74,
      phone: '(555) 678-9012',
      website: 'https://expresshvac.com',
      address: '987 Service Rd, Springfield',
      distance: 7.3,
      category: 'HVAC',
      hasWebChat: true,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    }
  ],
  plumber: [
    {
      id: 'plumber-1',
      name: 'Elite Plumbing Solutions',
      rating: 4.7,
      reviewCount: 156,
      phone: '(555) 111-2222',
      website: 'https://eliteplumbing.com',
      address: '321 Water St, Springfield',
      distance: 1.8,
      category: 'Plumbing',
      hasWebChat: true,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'plumber-2',
      name: '24/7 Emergency Plumbing',
      rating: 4.6,
      reviewCount: 94,
      phone: '(555) 222-3333',
      address: '654 Pipe Rd, Springfield',
      distance: 2.9,
      category: 'Plumbing',
      hasWebChat: false,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'plumber-3',
      name: 'Rapid Response Plumbing',
      rating: 4.8,
      reviewCount: 134,
      phone: '(555) 333-4444',
      website: 'https://rapidplumbing.com',
      address: '789 Flow St, Springfield',
      distance: 3.5,
      category: 'Plumbing',
      hasWebChat: true,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'plumber-4',
      name: 'Master Plumbers Inc',
      rating: 4.9,
      reviewCount: 201,
      phone: '(555) 444-5555',
      address: '147 Drain Ave, Springfield',
      distance: 4.2,
      category: 'Plumbing',
      hasWebChat: false,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'plumber-5',
      name: 'All Hours Plumbing',
      rating: 4.5,
      reviewCount: 87,
      phone: '(555) 555-6666',
      website: 'https://allhoursplumbing.com',
      address: '258 Emergency Ln, Springfield',
      distance: 5.8,
      category: 'Plumbing',
      hasWebChat: true,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    }
  ],
  electrician: [
    {
      id: 'electrician-1',
      name: 'Spark Electric Co.',
      rating: 4.9,
      reviewCount: 178,
      phone: '(555) 333-4444',
      website: 'https://sparkelectric.com',
      address: '987 Volt Ave, Springfield',
      distance: 2.1,
      category: 'Electrical',
      hasWebChat: true,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'electrician-2',
      name: 'Bright Light Electrical',
      rating: 4.4,
      reviewCount: 67,
      phone: '(555) 444-5555',
      address: '147 Current St, Springfield',
      distance: 3.8,
      category: 'Electrical',
      hasWebChat: false,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'electrician-3',
      name: 'PowerPro Electric',
      rating: 4.8,
      reviewCount: 145,
      phone: '(555) 555-7777',
      website: 'https://powerpro.com',
      address: '369 Electric Ave, Springfield',
      distance: 4.5,
      category: 'Electrical',
      hasWebChat: true,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'electrician-4',
      name: 'Lightning Fast Electric',
      rating: 4.6,
      reviewCount: 112,
      phone: '(555) 666-8888',
      address: '741 Voltage St, Springfield',
      distance: 5.1,
      category: 'Electrical',
      hasWebChat: false,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'electrician-5',
      name: 'Circuit Solutions',
      rating: 4.7,
      reviewCount: 89,
      phone: '(555) 777-9999',
      website: 'https://circuitsolutions.com',
      address: '852 Wire Way, Springfield',
      distance: 6.3,
      category: 'Electrical',
      hasWebChat: true,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    }
  ],
  roofer: [
    {
      id: 'roofer-1',
      name: 'Summit Roofing Co',
      rating: 4.9,
      reviewCount: 167,
      phone: '(555) 888-0000',
      website: 'https://summitroofing.com',
      address: '963 Peak Dr, Springfield',
      distance: 3.7,
      category: 'Roofing',
      hasWebChat: true,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'roofer-2',
      name: 'Elite Roofing Solutions',
      rating: 4.7,
      reviewCount: 134,
      phone: '(555) 777-8888',
      website: 'https://eliteroofing.com',
      address: '741 Shingle St, Springfield',
      distance: 4.2,
      category: 'Roofing',
      hasWebChat: false,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'roofer-3',
      name: 'Apex Roof Repair',
      rating: 4.8,
      reviewCount: 156,
      phone: '(555) 666-7777',
      address: '852 Gutter Ave, Springfield',
      distance: 5.3,
      category: 'Roofing',
      hasWebChat: true,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'roofer-4',
      name: 'Professional Roofers Inc',
      rating: 4.6,
      reviewCount: 98,
      phone: '(555) 555-6666',
      website: 'https://proroofers.com',
      address: '963 Tile Terrace, Springfield',
      distance: 6.1,
      category: 'Roofing',
      hasWebChat: true,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'roofer-5',
      name: 'Skyline Roofing Services',
      rating: 4.5,
      reviewCount: 87,
      phone: '(555) 444-5555',
      address: '147 Skyline Dr, Springfield',
      distance: 7.2,
      category: 'Roofing',
      hasWebChat: false,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    }
  ],
  pest: [
    {
      id: 'pest-1',
      name: 'Bug Busters Pest Control',
      rating: 4.8,
      reviewCount: 189,
      phone: '(555) 123-PEST',
      website: 'https://bugbusters.com',
      address: '456 Exterminator Ave, Springfield',
      distance: 2.8,
      category: 'Pest Control',
      hasWebChat: true,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'pest-2',
      name: 'Safe Home Pest Solutions',
      rating: 4.6,
      reviewCount: 134,
      phone: '(555) 234-5678',
      address: '789 Safe St, Springfield',
      distance: 3.5,
      category: 'Pest Control',
      hasWebChat: false,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'pest-3',
      name: 'Eco-Friendly Pest Control',
      rating: 4.9,
      reviewCount: 201,
      phone: '(555) 345-6789',
      website: 'https://ecopest.com',
      address: '321 Green Way, Springfield',
      distance: 4.1,
      category: 'Pest Control',
      hasWebChat: true,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'pest-4',
      name: 'Rapid Response Exterminators',
      rating: 4.7,
      reviewCount: 156,
      phone: '(555) 456-7890',
      address: '654 Quick Fix Rd, Springfield',
      distance: 5.2,
      category: 'Pest Control',
      hasWebChat: false,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'pest-5',
      name: 'All Seasons Pest Management',
      rating: 4.5,
      reviewCount: 98,
      phone: '(555) 567-8901',
      website: 'https://allseasonspest.com',
      address: '987 Season St, Springfield',
      distance: 6.3,
      category: 'Pest Control',
      hasWebChat: true,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    }
  ],
  general: [
    {
      id: 'general-1',
      name: 'HandyPro Services',
      rating: 4.6,
      reviewCount: 142,
      phone: '(555) 555-6666',
      website: 'https://handypro.com',
      address: '258 Fix-It Ln, Springfield',
      distance: 1.5,
      category: 'General Contractor',
      hasWebChat: true,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'general-2',
      name: 'All-in-One Home Services',
      rating: 4.7,
      reviewCount: 167,
      phone: '(555) 666-7777',
      address: '369 Service Blvd, Springfield',
      distance: 2.3,
      category: 'General Contractor',
      hasWebChat: false,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'general-3',
      name: 'Home Repair Experts',
      rating: 4.8,
      reviewCount: 189,
      phone: '(555) 777-8888',
      website: 'https://homerepairexperts.com',
      address: '741 Expert Ave, Springfield',
      distance: 3.1,
      category: 'General Contractor',
      hasWebChat: true,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'general-4',
      name: 'Quick Fix Contractors',
      rating: 4.5,
      reviewCount: 123,
      phone: '(555) 888-9999',
      address: '852 Quick St, Springfield',
      distance: 4.2,
      category: 'General Contractor',
      hasWebChat: false,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'general-5',
      name: 'Fix-It Appliance Repair',
      rating: 4.8,
      reviewCount: 142,
      phone: '(555) 999-0000',
      website: 'https://fixitappliance.com',
      address: '123 Repair St, Springfield',
      distance: 2.1,
      category: 'Appliance Repair',
      hasWebChat: true,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'appliance-2',
      name: 'Home Appliance Masters',
      rating: 4.6,
      reviewCount: 98,
      phone: '(555) 888-7777',
      address: '456 Service Ave, Springfield',
      distance: 3.4,
      category: 'Appliance Repair',
      hasWebChat: false,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'appliance-3',
      name: 'Quick Appliance Fix',
      rating: 4.7,
      reviewCount: 167,
      phone: '(555) 777-6666',
      website: 'https://quickappliancefix.com',
      address: '789 Fix Blvd, Springfield',
      distance: 4.2,
      category: 'Appliance Repair',
      hasWebChat: true,
      hasWhatsApp: true,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'appliance-4',
      name: 'Reliable Appliance Service',
      rating: 4.5,
      reviewCount: 123,
      phone: '(555) 666-5555',
      address: '321 Reliable Rd, Springfield',
      distance: 5.1,
      category: 'Appliance Repair',
      hasWebChat: false,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    },
    {
      id: 'appliance-5',
      name: 'HandyPro Services',
      rating: 4.6,
      reviewCount: 142,
      phone: '(555) 555-6666',
      website: 'https://handypro.com',
      address: '258 Fix-It Ln, Springfield',
      distance: 1.5,
      category: 'General Contractor',
      hasWebChat: true,
      hasWhatsApp: false,
      outreachStatus: 'pending',
      outreachLog: []
    }
  ]
};

export const findVendors = async (category: ProblemSummary['category'], zipCode: string): Promise<VendorData[]> => {
  // Simulate API call delay
  await new Promise(resolve => setTimeout(resolve, 2000));
  
  // In a real implementation, this would call Google Places API
  const placesType = CATEGORY_TO_PLACES_TYPE[category];
  console.log(`Searching for ${placesType} near ${zipCode}`);
  
  // Return sample vendors for the category
  const vendors = SAMPLE_VENDORS[category] || SAMPLE_VENDORS.general;
  
  // Add some randomization to distance and availability
  return vendors.map(vendor => ({
    ...vendor,
    distance: Math.round((0.3 + Math.random() * 12) * 10) / 10,
    id: `${vendor.id}-${Date.now()}-${Math.random().toString(36).substring(2, 9)}`,
    source: 'demo'
  }));
};